using System.Reflection;
using System.Runtime.CompilerServices;
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.RendererDetail))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.Cue))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.AudioStopOptions))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.SoundBank))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.WaveBank))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.AudioCategory))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Audio.AudioEngine))]
