using System.Reflection;
using System.Runtime.CompilerServices;
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.GestureType))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.GestureSample))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.TouchCollection))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.TouchLocationState))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.TouchPanelCapabilities))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.TouchLocation))]
[assembly: TypeForwardedToAttribute(typeof(FNA.Input.Touch.TouchPanel))]
